parameters:
  doctrine.orm.metadata.driver_chain.class: Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain

services:
  freyr.gallery.storage.photo:
    class: Freyr\Gallery\GalleryBundle\Storage\Cloudinary\CloudinaryPhotoStorage

  freyr.gallery.repository.photo:
    class: Freyr\Gallery\GalleryBundle\Repository\MongoDB\MongoDBPhotoRepository
    factory_service: doctrine_mongodb.odm.default_document_manager
    factory_method: getRepository
    arguments:
      - FreyrGalleryGalleryBundle:Photo

  freyr.gallery.service.photo:
    class: Freyr\Gallery\GalleryBundle\Service\PhotoService
    arguments: [ @freyr.gallery.repository.photo ]

  freyr.gallery.service.photo.raw:
    class: Freyr\Gallery\GalleryBundle\Service\RawPhotoService
    arguments: [ @freyr.gallery.repository.photo, @freyr.gallery.storage.photo ]

  freyr.twig.gallery_extension:
    class: Freyr\Gallery\GalleryBundle\Twig\CloudinaryExtension
    tags:
      - { name: twig.extension }

