<?php
/*
 * This file is part of the Gallery package.
 * (c) Michal Giergielewicz <michal@giergielewicz.pl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Freyr\GalleryBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Freyr\GalleryBundle\Document\Image;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends DocumentRepository
{
    /**
     * @param $keyword
     * @param $imageId
     * @return Image
     */
    public function getByKeywordAndId($keyword, $imageId)
    {
        return $this->findOneBy(["keyword" => $keyword, "id" => $imageId]);
    }

    /**
     * @param Image $image
     */
    public function save(Image $image)
    {
        $this->getDocumentManager()->persist($image);
        $this->getDocumentManager()->flush();
    }
}
