imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type:  console

doctrine_mongodb:
    connections:
        default:
            server: %mongolab.url%
            options: {}
    default_database: %mongolab.default_database%
    document_managers:
        default:
            auto_mapping: true
