<?php
/*
 * This file is part of the Gallery package.
 * (c) Michal Giergielewicz <michal@giergielewicz.pl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Freyr\Gallery\WebBundle\Repository\MongoDB;

use Doctrine\ODM\MongoDB\Cursor;
use Doctrine\ODM\MongoDB\DocumentRepository;

use Freyr\Gallery\Core\GalleryFactory;
use Freyr\Gallery\Core\GalleryInterface;
use Freyr\Gallery\Core\Entity\Image;

use Freyr\Gallery\Core\PhotoFactory;
use Freyr\Gallery\Core\PhotoInterface;
use Freyr\Gallery\Core\TagFactory;
use Freyr\Gallery\Core\TagInterface;
use Freyr\Gallery\WebBundle\Document\Gallery;
use Freyr\Gallery\WebBundle\Document\Tag;
use Freyr\Gallery\WebBundle\Document\Photo;
use Freyr\Gallery\WebBundle\Document\Property;

use Freyr\Gallery\WebBundle\Repository\PhotoRepositoryInterface;

/**
 * MongoDBPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MongoDBPhotoRepository extends DocumentRepository implements PhotoRepositoryInterface
{

    /**
     * @param Image $image
     * @param Property $storagePropertyInterface
     * @return PhotoInterface
     */
    public function persist(Image $image, Property $storagePropertyInterface)
    {
        $photo = new Photo();
        $photo->setProperty($storagePropertyInterface);
        $photo->setName($storagePropertyInterface->getPublicId());
        $gallery = new Gallery($image->getGallery());
        $photo->setGallery($gallery);
        $tags = [];
        foreach ($image->getTags() as $tag) {
            $tags[] = new Tag($tag);
        }
        $photo->setTags($tags);

        $this->getDocumentManager()->persist($photo);
        $this->getDocumentManager()->flush();

        return $photo;
    }

    /**
     * @return TagInterface[]
     */
    public function getTags()
    {
        /** @var Cursor $tags */
        $tags = $this->createQueryBuilder()->distinct('tags.name')->getQuery()->execute();

        return TagFactory::createMultipleTags($tags, 'Freyr\Gallery\WebBundle\Document\Tag');
    }

    /**
     * @return GalleryInterface[]
     */
    public function getGalleries()
    {
        /** @var Cursor $cursor */
        $cursor = $this->createQueryBuilder()->distinct('gallery.name')->getQuery()->execute();

        return GalleryFactory::createMultipleGalleries($cursor, 'Freyr\Gallery\WebBundle\Document\Gallery');
    }

    /**
     * @param GalleryInterface $gallery
     * @param int $randomizedSampleSize
     * @return Photo
     */
    public function assignPrimaryPhotoToGallery(GalleryInterface $gallery, $randomizedSampleSize)
    {
        /** @var Cursor $cursor */
        $images = $this->findBy(['gallery.name' => $gallery->getName()], ["limit" => $randomizedSampleSize]);
        $image = $images[array_rand($images)];
        $gallery->setPrimaryImage($image);
    }

    /**
     * @param TagInterface $tag
     * @param int $randomizedSampleSize
     * @return Photo
     */
    public function assignPrimaryPhotoToTag(TagInterface $tag, $randomizedSampleSize)
    {
        /** @var Cursor $cursor */
        $images = $this->findBy(['tag.name' => $tag->getName()], ["limit" => $randomizedSampleSize]);
        $image = $images[array_rand($images)];
        $tag->setPrimaryPhoto($image);
    }

    /**
     * @param string $imageId
     * @param TagInterface $tag
     * @return PhotoInterface
     */
    public function getPhotoByIdAndTag($imageId, TagInterface $tag)
    {
        return $this->findOneBy(["gallery.name" => $tag->getName(), "id" => new \MongoId($imageId)]);
    }

    /**
     * @param string $imageId
     * @param GalleryInterface $gallery
     * @return PhotoInterface
     */
    public function getPhotoByIdAndGallery($imageId, GalleryInterface $gallery)
    {
        return $this->findOneBy(["gallery.name" => $gallery->getName(), "id" => new \MongoId($imageId)]);
    }


    /**
     * @param TagInterface[] $tags
     * @return Cursor
     */
    public function getPhotosByTags(array $tags)
    {
        return $this->createQueryBuilder()
            ->field('gallery.name')
            ->in($tags)
            ->getQuery()->execute();
    }

    /**
     * @param GalleryInterface $gallery
     * @return PhotoInterface[]
     */
    public function getPhotosFromGallery(GalleryInterface $gallery)
    {
        $cursor = $this->createQueryBuilder()
            ->field('gallery.name')->equals($gallery->getName())
            ->getQuery()->execute();

        return PhotoFactory::createMultiplePhotos($cursor, 'Freyr\Gallery\WebBundle\Document\Photo');
    }
}
